[package]
name = "ray_tracer_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sorted-vec = "0.8.3"
rand = { version = "0.8.5", features = [] }